export const Products = [
  {
    id: 1,
    stock: 22,
    name: "Laura Mercier Caviar Stick Eye Color Sugar Frost 1.64g/0.05oz",
    ratting: 4.0,
    slug: "laura-mercier-caviar-stick-eye-color-sugar-frost-164g-005oz",
    reviews: 6,
    description:
      "Laura Mercier Caviar Stick Eye Color Sugar Frost 1.64g/0.05oz Caviar Stick Eye Shadow glides seamlessly onto lids. These eyeshadows are crease transfer and smudge resistant for long lasting even color payoff in a variety of shades and finishes. This easy-to-use versatile cream eye shadow stick delivers effortless application intense buildable color and up to 12-hour long lasting wear. Pick any pigment-rich eye shadow shade in creamy shimmer matte or chrome finish. Caviar Stick Eye Color glides seamlessly onto the lids remaining crease and transfer resistant. The luxe multi-use formulation allows you to easily smudge blend line fill or define eyes so you can effortlessly create any makeup look. An array of intense shades deliver endless options for alluring eyes that stand out both day and night. Dont be afraid to be playful! Caviar Stick Eye Shadow layers easily over or under other eye shadows including powder.",
    prices: {
      price: 22.9,
      originalPrice: 25.0,
    },
    picture:
      "https://i5.walmartimages.com/seo/Laura-Mercier-Caviar-Stick-Eye-Color-Sugar-Frost-1-64g-0-05oz_55297223-7af5-4a30-83c2-4d74d08969e3.8ca12dd7578ff564b6e01923e85ffd11.jpeg",
    contact: "+92-850-5585005",
    color: ["red", "blue"],
    categories: [
      "Beauty",
      "Makeup",
      "Eye Makeup",
      "Eye Shadow",
      "Eye Shadow Stick",
    ],

    size: [],
  },
  {
    id: 2,
    slug: "exultantex-grey-blackout-curtains-living-room-pom-pom-thermal-50x95",
    stock: 116,
    name: 'Exultantex Grey Blackout Curtains for Living Room,Pom Pom Thermal Window Curtains,50"W x 95"L, 2 Panels, Rod Pocket',
    ratting: 4.6,
    reviews: 58,
    description:
      '   ✨Soft triple weave fabric with a velvet-like texture   ✨Each panel measures 50"W x 95"L, sold in a set of 2 panels   ✨Adorned with charming gray pom-pom trimmings for a cozy atmosphere   ✨Suitable for various rooms: living room, kids room, bedroom, guest room   ✨Provides noise reduction and blocks at least 81% of light and UV radiation   ✨Thermal insulated to balance room temperature and reduce energy bills   ✨Easy installation with 3-inch rod pocket header   ✨Available in multiple colors and sizes   ✨Care instructions: Do not bleach, avoid pulling off pom poms, cool iron if necessary. Machine washable in a mesh bag, no dry cleaning needed  ',

    prices: {
      price: 47.88,
      originalPrice: 50.0,
    },
    picture:
      "https://i5.walmartimages.com/seo/Exultantex-Grey-Blackout-Curtains-for-Living-Room-Pom-Pom-Thermal-Window-Curtains-50-W-x-95-L-2-Panels-Rod-Pocket_f89aea0d-9d30-4bce-b65e-8c15732f1ca4.b20ae059333c322a0c8ea79bd569c7c7.jpeg",
    contact: "+92-807-2676317",
    color: [
      "Black",
      "Blue",
      "Green",
      "Gray",
      "Natural(Ivory)",
      "Navy(Royal Blue)",
      "Pink",
    ],
    categories: [
      "Home",
      "Decor",
      "Curtains & Window Treatments",
      "Curtains",
      "Blackout Curtains",
    ],
    size: ['50" x 54"', '50" x 63"', '50" x 84"', '50" x 95"'],
  },

  {
    id: 3,
    stock: 10,
    slug: "jessica-london-womens-plus-size-stretch-knit-v-neck-swing-tunic",
    name: "Jessica London Women's Plus Size Stretch Knit V-Neck Swing Tunic",
    ratting: 5.0,
    reviews: 2,
    description:
      "Jessica London Women's Plus Size Stretch Knit V-Neck Swing Tunic .Look no further for your new favorite tunic. We updated our bestselling swing tunic with short sleeves and a V-Neckline. The trapeze silhouette is made to flatter every body, and perfectly pairs with jeans or leggings for a great everyday outfit.&nbsp; Trapeze SilhouetteV NecklineAbove Elbow Sleeves30&quot; lengthRayon/SpandexMachine wash; Imported&nbsp;. About the brand: Style To Live By. Jessica London specializes in head-to-toe women’s plus size clothing outfitting that works for you—work days, special days, every day. Our classic designs come in plus sizes for women and offer easy, day-to-night versatility. Our professional collection keeps pace with your busy life. Plus, the most covetable accessories allow you to spin your look into something totally unique. After all, you can achieve anything - if you’re dressed for it!",

    prices: {
      price: 33.24,
      originalPrice: 35.0,
    },
    picture:
      "https://i5.walmartimages.com/seo/Jessica-London-Women-s-Plus-Size-Stretch-Knit-V-Neck-Swing-Tunic-1X-Raspberry_ad301f95-eee5-46f0-a07d-84befa229aee.b557dcd55539425f75e07446439149ca.jpeg",
    contact: "+92-244-4208941",
    color: [
      "Aqua Sea",
      "Dark Olive Green",
      "Dark Sapphire",
      "Navy",
      "Pink Burst",
      "Raspberry",
    ],
    categories: ["Clothing", "Womens Plus", "Plus Size Tops", "Plus Size Tops"],
    size: ["S", "M", "L", "1X", "2X", "3X"],
  },
  {
    id: 4,
    stock: 125,
    slug: "100-cotton-king-percale-duvet-set-blue-distress-tile-print",
    name: "100% Cotton King Percale Duvet Set (3 Piece) Blue Distress Tile Print by Simply Put",
    ratting: 4.7,
    reviews: 101,
    description:
      "Inspired by decorative blue and white tiles, the Simply Put 100% Cotton Distress Tile Print Duvet Set is a class above the ordinary. Made using 100% cotton, this top-quality set is soft and feels smooth against the skin, ensuring a luxurious night's sleep every time you bump in. In addition, the distress tile print on one side elevates the look of your bedroom decor like none other. This top-quality duvet set is certified by Standard 100 by OEKO-TEX which means it is made in environmentally friendly facilities under safe and socially responsible working conditions for credible safety and reliability.",
    prices: {
      // MODIFIED
      price: 49.99,
      originalPrice: 52.99,
    },
    picture:
      "https://i5.walmartimages.com/asr/d88fe658-b9fa-48fa-ad77-456edf23b3a5_2.017c4cd5ba8d3df3f9e3863ae7811e48.jpeg",
    contact: "+92-430-6059367",
    color: ["Beige", "Blue", "Gray", "Spa Blue"],
    categories: ["Home", "Bedding", "Duvet Covers", "King Duvet Covers"],
    size: ["Queen", "King"],
  },
  {
    id: 5,
    slug: "disney-boys-graphic-tee-donald-duck-short-sleeves-3-10t",
    stock: 55,
    name: "Disney Boys Graphic Tee Donald Duck Short Sleeves T-Shirt Top Summer Outfits Clothes Sizes 3-10T",
    ratting: 4.4,
    reviews: 15,
    description:
      "   Disney Toddler Boys Girls Graphic Tee, this short-sleeved tee is designed for girls boys and features beloved Disney characters graphic such as Mickey Mouse, Minnie Mouse, Donald Duck, and Daisy Duck.   The graphic tee has a moderate thickness, providing a balance between breathability and durability.   Suitable for various occasions, including Independence Day, Back to School, Start of School, and Thanksgiving Day, this graphic tee can be worn as part of casual summer outfits   Not See-Through: The Disney summer outfits' fabric is not see-through, ensuring your child's modesty   With its vibrant graphics and childlike design, this graphic tee captures the playful spirit of Disney and is sure to be loved by young boys   This Disney Toddler Boys girls Graphic T-shirt makes a great gift for little Disney fans  ",
    prices: {
      // MODIFIED
      price: 12.99,
      originalPrice: 14.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Disney-Boys-Graphic-Tee-Donald-Duck-Short-Sleeves-T-Shirt-Top-Summer-Outfits-Clothes-Sizes-3-10T_c2773cdf-d1b3-471a-9b40-20ab2d53817a.00bcaa73c02bc1af2a69dde8d6c3d28f.jpeg",
    contact: "+92-792-8813476",
    color: [
      "1#Yellow Micky",
      "2#Pink Minnie",
      "3#Blue Donald",
      "4#Purple Daisy",
      "5#Black Micky",
      "6#White Minnie",
      "7#Green Micky",
      "8#Blue Pluto",
      "9#Yellow Donald",
      "10#Grey Micky",
      "11#Blue strips",
      "12#Green strips",
      "13#Blue Stitch",
      "14#Daisy Purple",
      "15#Donald Blue",
      "16#Micky Red",
      "17#Minnie Pink",
    ],
    categories: [
      "Clothing",
      "Kids Clothing",
      "Boys Clothing",
      "Boys Outfit Sets",
    ],
    size: [
      "2T",
      "3T",
      "3T-4T",
      "3-4 Years",
      "4-5 Years",
      "4-5T",
      "5-6 Years",
      "5-6T",
      "6-7 Years",
      "6-7T",
      "7-8 Years",
      "7-8T",
      "8-9 Years",
      "8-9T",
      "9-10T",
      "9-10Years",
    ],
  },
  {
    id: 6,
    stock: 109,
    name: "Women's Vanity Fair 75201 Nearly Invisible Full Coverage Underwire Bra (Black 40C)",
    ratting: 4.4,
    reviews: 95,
    description:
      "   Amazing comfort in this seamless T-shirt bra   Supportive, no-poke underwire foam-lined plunge cups   Fully adjustable stretch straps for the perfect fit   3 column, 2 row hook &amp; eye closure; may increase with size   Smooth, stretch microfiber with a shimmery finish  ",
    prices: {
      price: 28.0,
      originalPrice: 32.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Women-s-Vanity-Fair-75201-Nearly-Invisible-Full-Coverage-Underwire-Bra-Black-40C_66b9371f-8786-422e-a20f-dc58d9c33726.54d6e7ba62e1150e89fcff45c95f592a.jpeg",
    contact: "+92-745-2215404",
    color: [
      "Cappuccino",
      "Damask Neutral",
      "Gray",
      "In The Buff",
      "Midnight Black",
      "Totally Tan",
    ],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Bras, Panties & Lingerie",
      "Womens Bras",
      "Underwire Bras",
    ],
    size: [
      "34B",
      "34C",
      "34D",
      "34DD",
      "36 D",
      "36C",
      "36DD",
      "38 B",
      "38B",
      "38D",
      "38DD",
      "40C",
      "40D",
      "40DD",
    ],
  },
  {
    id: 7,
    stock: 75,
    name: "IBTOM CASTLE Women's One Piece Rash Guard Swimsuit UV Protection Floral Printed Surfing Zipper Swimwear Bathing Suit Beachwear S Green Leaves",
    ratting: 4.3,
    reviews: 12,
    description:
      "❤❤【Bathing Suit for Women】Women's rash guard swim shirt top long sleeve swimsuit surf swim rashguard shirts boyleg bottoms swimwear swimming costume, fashion surfing wetsuit snorkeling suit UV protection swimwear one piece swimsuits for women, bathing suit for women, plus size swimwear for women, swimming costumes for women, long sleeve swimsuits for women, swimwear ladies ladies swimming costume, best gifts for her, mom, wife, girlfriend, sisters.  ❤❤【Swimsuit for Women】Women's long sleeve bathing suit floral print rash guard set is made of nylon, the material is soft, lightweight, soft and stretchy to wear, close fitted to the body, no itchy to the delicate skin, won't deform, fade or shrink easily after washing, providing you with a quite comfy experience. Dressing it up, can protect your body from UV rays and biological irritants in the sea. You will be the most charming lady on the beach or in the swimming pool.  ❤❤【Rash Guard Swimwear Design】Longer length swimwear, the short sleeve or long sleeve floral print one piece swimsuit for women, one piece rash guard padded bodysuit with zipper at front, can offer enough support and protection to your bust, easy to match. Long sleeve O neck swimsuit with sexy cutout at back, can be tied a bowknot at back for a comfortable fitting. Stylish cutout at back makes you look so sexy and seductive by showing your tender parts of the beck.  ❤❤【Occasion】Womens swimming costumes one piece bathing suits, longer length swimwear swimsuit women floral rash guard are perfect for swimming, beach party, vacation, SPA, resorts, summer, volleyball sport, exercise, workout, indoor or outdoor water activities. The tankini swimming suit, ruched one piece swimsuit swimwear retro vintage bathing suit swimming costume for women is suitable for women, ladies, maternity, mom, teens and juniors, also great for big busted curvy women.  ❤❤【Select Size】Womens one piece swimsuits tankini bathing suit swimwear size in S, M, L, XL, XXL. Please refer to left size image details before purchasing. One-piece swimming costume women with floral print is vivid and colorful, suitable for beach or swimming pool. Modest bathing suit for women, one piece swimsuit for women, gives you a sexy and charming look among the people.",
    prices: {
      price: 19.99,
      originalPrice: 24.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/IBTOM-CASTLE-Women-s-One-Piece-Rash-Guard-Swimsuit-UV-Protection-Floral-Printed-Surfing-Zipper-Swimwear-Bathing-Suit-Beachwear-S-Green-Leaves_51122fef-9613-491a-a10e-ab00636060d3.1d7b8c779d54a268b2281f2f265095c2.jpeg",
    contact: "+92-106-1314898",
    color: [
      "Black + Blue",
      "Black + Blue White",
      "Black + Gray",
      "Black + Green Leaves",
      "Black + Leopard",
      "Black + Orange",
      "Black + Pink Flower",
      "Black + Pink Leaves",
      "Black + Red Floral",
      "Black + Red Leaves",
      "Black + White Stripe",
      "Blue + Green Leaves",
      "Blue + Pink Backless",
      "Blue + Pink Floral",
      "Blue + Pink Leaves",
      "Blue + Pink Print",
      "Blue + Red Floral",
      "Blue + Yellow Floral",
      "Green + Pink Backless",
      "Green + Pink Floral",
      "Green Leaves",
      "Navy Blue",
      "Navy Blue + Pink Leaves",
      "Pink + Yellow Floral",
      "Pink Backless",
      "Sky Blue Leaves",
      "Yellow Flower",
    ],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Swimsuits",
      "Womens One-Piece Swimsuits",
      "Womens One-piece Swimsuits",
    ],
    size: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 8,
    stock: 12,
    name: "a.Jesdani Women's Cardigan Classic Casual Lightweight Knit Cardigan Sweaters S-XXL",
    ratting: 4.2,
    reviews: 336,
    description:
      "   This cardigan sweater is simple, casual, elegant, and suitable for any woman.   Material: 80% viscose fiber, 20% nylon, soft and comfortable fabric, light and skin-friendly   Features: This Women's Open Front Casual Long Sleeve Knit Classic Sweaters Cardigan with Pockets for women has the ribbing on the sleeves and bottom shawl collar, long sleeve, solid color, not wrinkle easily. They are lightweight for season change! The cardigans layer well with tank top, camisoles, blouse or T-shirt for a nice classic look. Knitted fabric feels luci ously soft to the touch. You could wear it to church, market, work, trip or at home. You would love it.   Mix: Open front cardigans for women fit well with tank top, casual t-shirt, jeans, dress,leggings.   Occasion: good for spring, fall ,winter. Could wear to party, dating, daily wear, office, vacation, weekend. Layer well with tank top, camisoles, blouse or T-shirt, jeans, dress,leggings.    Product Description         Tittle:a.Jesdani Women's Open Front Casual Long Sleeve Knit Classic Sweaters Cardigan with Pockets     Cardigan Sweaters for Women Clothing Care: Hand Wash, Do not use bleach, Hang dry     Type:Sweaters Cardigans     Pattern&nbsp;Type:Classic     Sleeve&nbsp;length:long&nbsp;sleeve     Womens Cardigans Long Sleeve Colors:Black, White, Navy, Heather gray, Light pink, Royal Blue, Mustard, Burgundy, Red.     Sweaters for Women Size     Small US4-6, Medium US 8-10, Large US 12-14, X-Large US 16-18.     There is 2-3% difference according to manual measurement.     Womens Sweaters Cardigans Color Disclaimer : Due to monitor settings monitor pixel definitions we cannot guarantee that the color you see on your screen as an exact color of the product.     We hope that every woman who wears ours clothes will be more confident, beautiful and happy to enjoy life. If you love this Womens Cardigan Sweaters, ”Add to Cart\" now.      ",
    prices: {
      price: 22.99,
      originalPrice: 28.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/a-Jesdani-Women-s-Cardigan-Classic-Casual-Lightweight-Knit-Cardigan-Sweaters-S-XXL_9ffcabe3-1093-45c1-9d53-88eb2b7e84b1.267ee80039d689cb99b3e82193eb15d7.jpeg",
    contact: "+92-562-6097826",
    color: [
      "A1-Black",
      "A2-White",
      "A3-Camel Heather",
      "A4-Burgundy",
      "A5-Navy Blue",
      "A6-Light Grey",
      "A7-Mustard",
      "A8-Charcoal Black",
      "A9-Heather Grey",
      "A10-Green",
      "A11-Light Pink",
      "NEW11-Light Pink",
      "A12-Light Purple",
      "A13-Royal Blue",
      "NEW13-Royal Blue",
      "A14-Light Blue",
      "A15-Rose",
      "NEW16-Yellow",
    ],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Workwear",
      "Womens Workwear Sweaters",
    ],
    size: ["S", "M", "L", "XL", "XXL"],
  },
  {
    id: 9,
    stock: 134,
    name: "4th of July Women’s Lounger Sleepshirt by Way To Celebrate, Sizes S to 3X",
    ratting: 4.7,
    reviews: 203,
    description:
      "You’re the queen of the comfort sleepshirt! Add this bold Lounger Sleepshirt from Way to Celebrate to your collection. Crafted in a soft blend of polyester and spandex for a soft and gentle feel against your skin for a peaceful sleep. Finished with a fun, playful graphic in an adorable V-neck style. It’s super cute and cozy for lounge about days and catching ZZZs.",
    prices: {
      price: 6.09,
      originalPrice: 7.99, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/4th-of-July-Women-s-Lounger-Sleepshirt-by-Way-To-Celebrate-Sizes-S-to-3X_44136af5-6e4b-487f-8073-271123862f61.c806a7fe5111a72de924a49b07ef4b77.jpeg",
    contact: "+92-394-4692642",
    color: ["Blue Cove", "Brilliant Red", "Completely Pink", "Tea Rose"],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Pajamas & Loungewear",
      "Womens Nightshirts & Gowns",
    ],
    size: ["S", "M", "L", "XL", "2X", "3X"],
  },
  {
    id: 10,
    stock: 127,
    name: "Vulcanodon Mens Pajama Set 100% Cotton, Long Sleeve Button Down PJ Set for Men Plaid Men's Sleepwear(Red Blue-Plaid, Large)",
    ratting: 4.6,
    reviews: 68,
    description:
      "   Ultra Soft Material: The mens pajama set made of cotton fabric, it have super soft sense of hand ,Sweat-absorbent and breathable.SThe design of long-sleeved trousers is warm and comfortable, suitable for spring and autumn nights.The pajamas are perfect for wear morning or throughout the year when you sleep or lounging.   Classic design: The soft mens pajama sets with classic lapel and plaid design. The pjs with button front and a notch collar, chest pocket，The woven process makes the pajamas more neat and stylish，Pants have a front fly.   Perfect fit: Whatever your build or frame, the loose style sets are fit for all shapes.Soft pajama pants have an elastic waist and drawstring so you can loosen or tighten them as much as you want.You’ll love the loose fit that ensures no restriction as you relax or slumber.   Two pockets:The sleepwear for men features two roomy pockets, it can keep small items close, such us phone, keys. Once you put on this pajama set, you will enjoy the convenience of the two pockets.   Nice gift: The soft men pajamas are Perfect Gift for your father, husband，friend, It’s the most warming present for Christmas, New Year, Valentine’s Day, Father’s Day or his birthday.Giving a Surprise for him right away!  ",
    prices: {
      price: 24.99,
      originalPrice: 30.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Vulcanodon-Mens-Pajama-Set-100-Cotton-Long-Sleeve-Button-Down-PJ-Set-for-Men-Plaid-Men-s-Sleepwear-Red-Blue-Plaid-Large_19f5ab18-9477-4d70-be8a-7b8298dcce0d.2571a25fbe8b6ebe7abafd2c59231fc6.jpeg",
    contact: "+92-504-5658441",
    color: [
      "Aqua Blue-Plaid",
      "Dark Blue-Plaid",
      "Navy-Plaid",
      "Red Blue-Plaid",
      "Royal Blue-Plaid",
    ],
    categories: [
      "Clothing",
      "Mens Clothing",
      "Mens Pajamas and Robes",
      "Mens Pajama Sets",
    ],
    size: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: 11,
    stock: 136,
    name: "Grande Cosmetics GrandeLash MD Eyelash Formula, 2mL (New Packaging)",
    ratting: 4.6,
    reviews: 6356,
    description:
      "Who needs false lashes when you have GrandeLash MD Lash Enhancing Serum? This eyelash serum increases both the thickness and length of your lashes to give you the look you want in just a few months.It nourishes your lashes with a combination of antioxidants, vitamins and amino acids. It is perfect for those with naturally thin or short eyelashes as well as those with damaged lashes.",
    prices: {
      price: 36.98,
      originalPrice: 40.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/GrandeLash-MD-Serum-Lash-Enhancing-0-07-oz-3-Month-Suply_92438031-adc5-43a0-97c2-88ca22342a8b.34f0a41a8312b1077f80d9b14355007c.jpeg",
    contact: "+92-805-6446409",
    color: [],
    categories: [
      "Beauty",
      "Makeup",
      "Eye Makeup",
      "Mascara",
      "Eyelash Enhancer",
    ],
    size: ["2 mL"],
  },
  {
    id: 12,
    stock: 56,
    name: "nuLOOM Vintage Erline Area Rug",
    ratting: 4.7,
    reviews: 49,
    description:
      "100% Polypropylene,100% Polypropylene, made in Turkey,Designed with resilience against everyday wear-and-tear, this rug is kid and pet friendly and perfect for high traffic areas of your home such as living room, dining room, kitchen, and hallways,Sleek and functional 0.43 pile height allows for convenient placement in entryways, underneath furniture, and will not obstruct doorways,Brimming with artistic charm, bohemian rugs help you unleash your creativity,Easy to clean and maintain, we recommend vacuuming regularly and spot treating any mild stains with carpet cleaner",
    prices: {
      price: 46.49,
      originalPrice: 55.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/nuLOOM-Vintage-Erline-Area-Rug_ced07d55-ed2d-4dec-9020-97ce527bd5cd.bf636aba1ebb0c219e829f63320dd778.jpeg",
    contact: "+92-277-3833790",
    color: ["Black", "Multi"],
    categories: ["Home", "Decor", "Floor Decor"],
    size: ["2' 6\" x 10'"],
  },
  {
    id: 13,
    stock: 67,
    name: "Georgia Giant Work Boot Size 10.5(W)",
    ratting: 4.5,
    reviews: 242,
    description:
      "These boots are about comfort and quality. They're Georgia Giant Work Boots.The upper of these work boots features full-grain brown leather, a bumper guard (great for resisting abrasions) and a lace-up design that allows you to adjust the fit of the footwear for maximum comfort.The interior of the men's work boots is lined; this helps maintain the interior, helps keep your feet dry and it feels soft. A steel shank gives you steady footing and supports your arches. A mesh-covered cushioned insole provides comfort to your feet throughout the day.The footwear is built with Goodyear&reg; welt construction. This type of construction enhances the boot's strength and durability, allowing them to hold up better on the job. It also allows you to have the outsole repaired easily and inexpensively once it begins to wear down.The polyurethane Georgia Giant outsole is lightweight, supplies great cushioning and flexibility, and is resistant to chemicals and oil.If you need comfortable boots, these Georgia Boots are a great choice!",
    prices: {
      price: 123.0,
      originalPrice: 135.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Georgia-Giant-Work-Boot-Size-10-5-W_df9f8afd-ac3e-4f43-85ea-666acfbcb2b4.fa428e726c279c5df1b560b4103e3d1f.jpeg",
    contact: "+92-207-7798789",
    color: ["Brown"],
    categories: ["Clothing", "Shoes", "Mens Shoes", "Mens Wide Shoes"],
    size: [
      "6.5",
      "7",
      "7.5",
      "8",
      "8.5",
      "9",
      "9.5",
      "10",
      "10.5",
      "11",
      "11.5",
      "12",
      "13",
      "14",
      "15",
      "16",
      "17",
    ],
  },
  {
    id: 14,
    stock: 83,
    name: "Amay 800 Thread Count 100% Organic Cotton Short Queen Size 1PC Flat Sheet (90x102 ) Pink Striped",
    ratting: 5.0,
    reviews: 8,
    description:
      "   FLAT SHEETS DIMENSION -Short Queen 1Pc Flat Sheet Only 90 wide and 102 inches long   100% ORGANIC COTTON - Certified with GOTS (Global Organic Textile Standard), fine yarn (made with long staple cotton fibers) in a single ply is used to make this amazingly soft 800 thread count fabric. Switch to non-toxic &amp; chemical free bedding that is luxurious &amp; durable.   CERTIFIED STANDARD 100 by OEKO-TEX - All our products are MADE IN GREEN and STANDARD 100 by OEKO?TEX. According to the guidelines, these products are tested for harmful substances and produced in an environmentally friendly and socially responsible manner. Each fabric batch is also tested for various durability features such as no-pilling, low shrinkage, color fastness etc., then stitched, individually inspected to be defect free and finally packed for sales   FEEL THE DIFFERENCE - Sleep better and wake up each morning feeling refreshed and full of energy. Best for any room in your house - bedroom, guest room, kids room, RV, vacation home. Great gift idea for men and women, Moms and Dads, Valentine's - Mother's - Father's Day and Christmas.   PEACE OF MIND: Our team’s first priority is keeping you happy with your purchase! We are passionate about what we do and proud of the products we offer. If you have any questions or concerns, please don’t hesitate to contact us. We will be quick to respond!  ",
    prices: {
      price: 49.5,
      originalPrice: 60.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Amay-800-Thread-Count-100-Organic-Cotton-Short-Queen-Size-1PC-Flat-Sheet-90x102-Pink-Striped_6ddd474a-f6df-41c0-90c0-10b3f6c039c2.a08cb7e481300b72632c08ad51ef5675.jpeg",
    contact: "+92-627-1409109",
    color: [
      "Aqua Blue",
      "Beige",
      "Black",
      "Burgundy",
      "Chocolate",
      "Dark Grey",
      "Gold",
      "Gray",
      "Hot Pink",
      "Ivory",
      "Lavender",
      "Light Blue",
      "Navy Blue",
      "Orange",
      "Parrot Green",
      "Peach",
      "Pink",
      "Purple",
      "Red",
      "Royal Blue",
      "Sage",
      "Silver Gray",
      "Silver Grey",
      "Taupe",
      "Teal",
      "Turquoise",
      "White",
      "Wine",
      "Yellow",
    ],
    categories: [
      "Home",
      "Bedding",
      "Bed Sheets & Pillowcases",
      "Colored Sheets",
    ],
    size: [
      "King Pillowcases(20x40)",
      "Queen Pillowcases(20x30 )",
      "Twin(66x96)",
      "Twin XL(70x102)",
      "Full(81x96)",
      "Olympic Queen( 90x102)",
      "Queen( 90x102)",
      "Short Queen( 90x102)",
      "California king(102x110)",
      "King(102x108)",
      "RV King(102x108)",
      "Split King(102x108)",
      "Emperor(110x125)",
      "Grand King(110x125)",
      "Alaska King(125x125)",
    ],
  },
  {
    id: 15,
    stock: 99,
    name: "Hard Tail Women's French Terry Sweatshirt and Pant Set, 2-Piece, Sizes S-3X",
    ratting: 4.2,
    reviews: 11,
    description:
      "Stay cozy and stylish with the Hard Tail Women's French Terry Sweatshirt and Pant Set. This 2-piece set, available in sizes S to 3X, is crafted from ultra-soft French terry fabric, offering unmatched comfort for lounging or casual outings. The sweatshirt features a relaxed fit with a classic crew neckline and ribbed cuffs, while the matching pants boast an elastic waistband and tapered legs for a flattering silhouette. Perfect for mixing and matching with your wardrobe, this set provides effortless style and all-day comfort. Elevate your casual wear with this versatile and chic French terry set from Hard Tail.",
    prices: {
      price: 44.88,
      originalPrice: 50.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Hard-Tail-Women-s-French-Terry-Sweatshirt-and-Pant-Set-2-Piece-Sizes-S-3X_e9b8a0b2-b7de-4491-bd4e-973c028a8906.b1835f52e27909aeb4066120faf69eb1.jpeg",
    contact: "+92-265-5069285",
    color: ["Chiseled Stone", "Coca Mocha", "Deep Depths", "Sandshell"],
    categories: ["Clothing", "Womens Clothing", "Womens Two Piece Sets"],
    size: ["S", "M", "L", "XL", "1X", "XXL", "2X", "3X"],
  },
  {
    id: 16,
    stock: 8,
    name: "Men's The Little Mermaid Vintage Characters  Graphic Tee Turquoise Medium",
    ratting: 5.0,
    reviews: 9,
    description:
      "   Enjoy comfort and fashion at the same time with this unique Men's graphic T Shirt from The Little Mermaid.   Strut your stuff with this stylish new Men's Tee Shirt that is perfect for every occasion! Featuring your favorite characters like Ariel, Flounder, King Triton, Sebastian, Ursula.   Find the perfect fit for you! Check out size charts for more information. Made from the highest quality materials on first-class digital direct-to-garment printers. *This item is made to order please consider this when ordering multiple sizes.*   Printed In the U.S.A with safe water-based inks. Easy care; machine wash cold inside out with similar colors, tumble dry low, (hang dry for best results).   Officially licensed apparel. Designed by an exclusive collaboration with top brands &amp; world-class artists.  ",
    prices: {
      price: 14.99,
      originalPrice: 18.99, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Men-s-The-Little-Mermaid-Vintage-Characters-Graphic-Tee-Turquoise-Medium_3797aac5-b895-49c0-a8b2-302426648d30_1.c25de960403f04ea32b746c9ec779f0a.jpeg",
    contact: "+92-565-1133847",
    color: ["Light Blue", "Turquoise"],
    categories: [
      "Clothing",
      "Graphics Shop",
      "Graphic Tees",
      "Disney Tees",
      "Men's Disney Tees",
    ],
    size: ["Big & Tall", "Men", "S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 17,
    stock: 12,
    name: "Aiyino Women's High Waist Yoga Pants Tummy Control Slimming Booty Leggings Workout Running Butt Lift Tights",
    ratting: 3.0,
    reviews: 2,
    description:
      "   Top A+ MATERIAL- Polyester/Spandex. Smooth and Ultra-Soft Fabric that provides extreme comfort with very little weight without restriction. It gives your butt a streamlined look like a Juicy peach. Plus a butt lifting feature for a natural looking back.   BUTT LIFTING LEGGINGS - 2022 Newest Tik Tok Leggings is both affordable and accessible, perfect for fitness enthusiasts and everyday athleisure. Operating at the cross section between fashion and function. Our custom design and comfortable feel are a second skin without the worry of possible irritation or chaffing on the insides of your thighs.   All-PURPOSE PANTS - The high quality activewear is both affordable and accessible, perfect for fitness enthusiasts and everyday athleisure. Operating at the cross section between fashion and function. Our custom design and comfortable feel are a second skin without the worry of possible irritation or chaffing on the insides of your thighs. Suitable for yoga, exercise, fitness, running, any type of workout, or everyday use.   HIGH WAIST DESIGN - Using 4 way Stretch &amp; Non See-through Fabric that slims, conforms, and contours with each pose and movement. It provides lightweight comfort along with sweat absorption and moisture wicking capabilities. find. workout yoga pants designed with high-waist, tummy control wide waistband to provide a smooth secure fit and show your figure off to perfection  ",
    prices: {
      price: 14.99,
      originalPrice: 20.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Aiyino-Women-s-High-Waist-Yoga-Pants-Tummy-Control-Slimming-Booty-Leggings-Workout-Running-Butt-Lift-Tights_dc3b201c-4258-4a18-b585-6381d38e2cfc.f6e58a5d1ef425e4ff5c02db9096b134.jpeg",
    contact: "+92-945-4423173",
    color: ["Black", "KD Black", "KD PS Grey", "PS Grey"],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Activewear",
      "Womens Workout Bottoms",
      "Womens Workout Bottoms",
    ],
    size: ["S", "M", "L", "XL", "2XL"],
  },
  {
    id: 18,
    stock: 45,
    name: "Jockey Women's Rib Knit Tee",
    ratting: 4.0,
    reviews: 86,
    description:
      "For sunny days or just hanging around the house, the Jockey Rib Knit Tee is the top you'll always reach for. Silky-soft fabric with a bit of stretch offers a flattering fit that feels great, right down to the tag-free neckline. With a length that's just right, pair this easy tee with everything from leggings to jeans for a casual look that just works.",
    prices: {
      price: 19.99,
      originalPrice: 25.0, // Adjusted originalPrice
    },
    picture:
      "https://i5.walmartimages.com/seo/Jockey-Women-s-Rib-Knit-Tee_bdf85bc8-cb86-4dd9-9187-767547a35abb.7642045ba0d7b2802f818f5a99053f0d.jpeg",
    contact: "+92-151-4491701",
    color: [
      "Black",
      "Dusk Blue Heather",
      "Dusty Mauve",
      "Light Grey Heather",
      "Mountain Green",
      "Oatmeal Heather",
      "Warm Cider",
      "White",
    ],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Tops",
      "Tshirts for Women",
      "Tshirts for Women",
    ],
    size: ["XS", "S", "M", "L", "XL", "1X", "2XL", "3XL"],
  },
  {
    id: 19,
    stock: 91,
    name: "Bare Home Cozy Fleece Sheet Set - Extra Plush Polar Fleece - Deep Pocket - Split King, Black",
    ratting: 4.8,
    reviews: 483,
    description:
      "Bare Home Cozy Fleece Sheet Set - Extra Plush Polar Fleece - Deep Pocket - Split King, Black Experience the Bare Home Cozy Fleece Sheet Set for a comfortable and cozy night's sleep. Our fleece queen bed sheets are great for wicking away moisture and humidity as well as being lightweight and breathable. Our design is pill, stain, and fade resistant. It is a great alternative for those allergic to wool and flannel sheets. The fleece&nbsp;queen fitted sheet is fully elasticized and designed to fit any mattress up to 15 inches deep. These sheets are sure to keep you warm for maximum sleep comfort on cold nights. Machine wash in cold water with similar colors. Dries quickly on tumble dry low temperature.",
    prices: {
      price: 64.99,
      originalPrice: 79.99,
    },

    picture:
      "https://i5.walmartimages.com/seo/Bare-Home-Cozy-Fleece-Sheet-Set-Extra-Plush-Polar-Fleece-Deep-Pocket-Split-King-Black_192f58d3-11a4-4c8d-9e2b-cb782e236297.9b2d18407a717f44e10f99a953557d4c.jpeg",
    contact: "+92-316-4534305",
    color: [
      "Black",
      "Cocoa",
      "Coronet Blue",
      "Cream",
      "Cypress",
      "Dark Blue",
      "Forest Green",
      "Gray",
      "Light Blue",
      "Light Gray",
      "Light Pink",
      "Red",
      "Sand",
      "Taupe",
      "White",
    ],
    categories: [
      "Home",
      "Bedding",
      "Bed Sheets & Pillowcases",
      "Colored Sheets",
    ],
    size: [
      "Twin",
      "Twin-XL",
      "Full",
      "Queen",
      "King",
      "California King",
      "Full-XL",
      "Split Head Flex King",
      "Split King",
    ],
  },
  {
    id: 20,
    stock: 79,
    name: "Zenana Womens & Plus Stretch Cotton Foldover Waist Bootcut Workout Yoga Pants",
    ratting: 3.7,
    reviews: 131,
    description:
      'Size Type: Zenana Womens &amp; Plus Stretch Cotton Foldover Waist Bootcut Workout Yoga Pants are in stock and ready to ship via USPS. Make sure to purchase the Zenana Womens &amp; Plus Stretch Cotton Foldover Waist Bootcut Workout Yoga Pants from "TheLovely" for your satisfaction and quality guaranteed. "TheLovely" is the only retailer that carries the legitimate Zenana Womens &amp; Plus Stretch Cotton Foldover Waist Bootcut Workout Yoga Pants at Walmart.com with free shipping and free return service at no charge. Please look out the counterfeit sold by "Timeless Gala"  Special Style: These Fold Over Yoga Flare Pants feature High Fold Over Waistband, Flared Hemline and Pull on Closure. These Zenana\'s yoga flared bottom pants are contouring perfectly to your body, giving you a streamlined look. A contoured, wide waistband with flex back design follows your natural body lines and highlight your peachy hip line more effectively. These high waisted yoga pants are made from moisture-wicking and breathable fabric designed to remove moisture from your body, provide lightweight comfort along with sweat absorption and drying capabilities.  Measurement :   [S]- (Fits 2/4-6) Waist: 27in , Inseam: 32in   [M]-(Fits 6-8) Waist: 29in , Inseam: 32.5in   [L]-(Fits 10-12) Waist: 31in , Inseam: 33in   [XL]-(Fits 12-14) Waist: 33in , Inseam: 33.5in   [1X]-(Fits 14-16) Waist: 35in , Inseam: 33in   [2X]-(Fits 16-18) Waist: 37in , Inseam: 33.5in   [3X]-(Fits 18-20) Waist: 39in , Inseam: 34in  Model size : 5\'3" height, 33" bust, 24" waist, 34" hip, and is wearing a size S, Fits true to Womens size, take your normal size  Material: 95% cotton 5% spandex - Incredibly soft and super comfortable. * * CHARCOAL, H BEIGE, ASH OLIVE FABRIC CONTENTS: 60% COTTON 35% POLYESTER 5% SPANDEX  Pattern: Solid  Available Size: S, M, L, XL, 1X, 2X, 3X  Feedback fro Customers *I’m very happy with these! I’m 5’9”, 160lbs and I got a medium. Fit is great! Very high waist (if you don’t fold it over) which I like. Also they are PLENTY long.  *Great fit. These pants are long - I have a 33” inseam and they fit half-inch or so long (haven’t washed them yet) but very comfortable. Will buy again * At 183 pounds and a 44-inch hips, the XL fits perfectly (I might even be able to go down a size, but I\'ll wait and see how drastically these shrink in the wash). They are not too thin, or too thick, they are wonderful!  Shipping: USPS Flat Shipping  Availability: In Stock! Ready to ship within 24 hours!',
    prices: {
      price: 11.89,
      originalPrice: 18.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Zenana-Womens-Plus-Stretch-Cotton-Foldover-Waist-Bootcut-Workout-Yoga-Pants_79f044df-5e15-487d-94c4-6036e8f2c335.5791910c2a671d0bde814367c60e19d3.jpeg",
    contact: "+92-372-7943407",
    color: [
      "2PK: Ash Grey/Charcoal",
      "2PK: Ash Mocha/Deep Camel",
      "2PK: Ash Rose/Magenta",
      "2PK: Black/White",
      "2PK: Charcoal/ Grey",
      "2PK: Charcoal/Grey",
      "2PK: DK Olive/LT Olive",
      "2PK: Deep Sky/Spring Blue",
      "2PK: LT Navy/LT Olive",
      "2PK: LT Navy/Mint",
      "2PK: NAVY/TEAL",
      "2PK: Neon Coral/ Mauve",
      "2PK: Neon Coral/H Mauve",
      "2PK: Neon Coral/Mauve",
      "2PK: Olive Mustard/Khaki",
      "2PK: Ruby/Magenta",
      "2PK:Bone/ Beige",
      "2PK:Bone/Beige",
      "2PK:Bone/H Beige",
      "3PK: Ash Rose/Ruby/DK Burgundy",
      "3PK: Black/Charcoal/ Grey",
      "3PK: Black/Charcoal/Grey",
      "3PK: Black/Charcoal/H Grey",
      "3PK: Black/Charcoal/White",
      "ASH MUSTARD",
      "ASH OLIVE",
      "Americano",
      "Army Green",
      "Ash Grey",
      "Ash Mocha",
      "Ash Rose",
      "Beige",
      "Black",
      "Blue Grey",
      "Bone",
      "Charcoal",
      "Copper",
      "DK Burgundy",
      "DK Olive",
      "DK Plum",
      "DK Rust",
      "Deep Camel",
      "Deep Sky",
      "Denim Blue",
      "Desert Rose",
      "Dusty Banana",
      "Dusty Teal",
      "Eggplant",
      "Fuchsia",
      "Green",
      "Grey",
      "H Beige",
      "H Mauve",
      "Hunter Green",
      "Ivory",
      "KHAKI",
      "LT NAVY",
      "LT Olive",
      "Magenta",
      "Mauve",
      "Mint",
      "Mocha",
      "Navy",
      "Neon Coral",
      "Olive Mustard",
      "Ruby",
      "Spring Blue",
      "Teal",
      "White",
    ],
    categories: [
      "Sports & Outdoors",
      "Bikes",
      "Bike Apparel & Footwear",
      "Cycling Pants",
    ],
    size: [
      "S",
      "M",
      "L",
      "XL",
      "1X",
      "2X",
      "3X",
      "Large",
      "Medium",
      "Small",
      "X",
      "X-Large",
    ],
  },
  {
    id: 21,
    stock: 53,
    name: "SONGMICS 3-Tier Shoe Rack with Shelves for Closet Entryway Black",
    ratting: 4.4,
    reviews: 58,
    description:
      "   Non-Woven fabric, metal tube, plastic connector   With a length of 38.8'', 4-5 pairs of shoes can comfortably sit on each shelf, totaling to 12-15 pairs. The 6.7'' spacing between the shelves allows you to store any type of footwear, from sneakers to high heels   Parts separated in different bags, labeled parts, and clear instructions provide you with everything you need to put this 3-tier shoe rack together quickly and easily   Constructed with non-woven fabric shelves, metal tube frames, and sturdy plastic connectors, this shoe rack is lightweight yet strong to hold up to 11 lb. Per tier   This slim, vertical shoe rack maximizes your storage space in the entryway or closet while minimizing floor space, making it ideal for small spaces  ",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/SONGMICS-3-Tier-Shoe-Rack-with-Shelves-for-Closet-Entryway-Black_96cf6d35-2e48-4c59-9e02-67e317c60eb1.f89f327b9b80f7e452b570e3f1c52720.jpeg",
    contact: "+92-208-9336410",
    color: ["Black"],
    categories: [
      "Home",
      "Storage & Organization",
      "Closet Organizers",
      "shoe storage",
      "Shoe Racks",
    ],
    size: ["2 tier", "3 tier", "4 tier", "5 Tiers", "10 tier"],
  },
  {
    id: 22,
    stock: 20,
    name: "MOSHU Summer Womens Tank Tops U Neck Casual Flowy Sleeveless Shirts for Women",
    ratting: 4.5,
    reviews: 1667,
    description:
      "MOSHU Summer Womens Tank Tops U Neck Casual Flowy Sleeveless Shirts for Women  Summer womens tank tops is a sleeveless u-neck solid color sleeveless shirts with a low cut curved hem that adds a touch of cuteness and glamour, the tunic tank tops for women is lightweight and has a comfortable fabric that is comfortable and cool in hot weather.Loose fitting style and long enough to drapes over your belly with room to spare but still looks stylish.Womens tops is sure to make a statement wherever you go. The sleeveless design ensures you stay comfortable all day, making the tank tops for women the perfect choice for hot summer days.  # Size Chart  S&nbsp; Bust 96 cm, Length 68 cm, Hem 106 cm  M&nbsp; Bust 100 cm, Length 70 cm,Hem 110 cm  L&nbsp; Bust 106 cm, Length 72 cm, Hem 116 cm  XL&nbsp; Bust 114 cm, Length 74 cm, Hem 124 cm  2XL&nbsp; Bust 124 cm, Length 76 cm,Hem 134 cm  3XL&nbsp; Bust 136 cm, Length 78 cm,Hem 146 cm  Note:  There may be 1-3cm deviation in different sizes, locations and stretch of fabrics.Size chart is for reference only; There may be a little difference with what you get.Color may be lighter or darker due to the different PC display.",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/MOSHU-Summer-Womens-Tank-Tops-U-Neck-Casual-Flowy-Sleeveless-Shirts-for-Women_d89f6185-7408-4809-8abc-2fd578ae035a.d83a552d020c479c9e7bba2049c0f2fc.jpeg",
    contact: "+92-512-8107823",
    color: [
      "4-st Clover",
      "Black",
      "Coffee",
      "Coral",
      "Dark Green",
      "Dark Purple",
      "Gray",
      "Grey Blue",
      "Lake Blue",
      "Ligth Green",
      "Navy",
      "Purple",
      "White",
    ],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Tops",
      "Womens Tank Tops",
      "Womens Tank Tops",
    ],
    size: ["S", "M", "L", "XL", "2XL", "3XL"],
  },
  {
    id: 23,
    stock: 129,
    name: "Victorious Men's Skinny Fit Unwashed Raw Denim Jeans DL938 - Indigo - 32/30",
    ratting: 5.0,
    reviews: 1,
    description:
      'Our Victorious Men\'s Skinny Fit Unwashed Raw Denim Jeans are perfect for the guy who\'s on top of his style game. Features a cotton poly blend with added stretch to be comfortable throughout the day while being stylish and fitting. Victorious pants have a slim fit but not tight at all with the basic 5 pocket styling. The color maintains it\'s richness and material is durable to not rip easiliy without being stiff or scratchy. Choose a darker wash to dress up your look, or go casual with a pop of color. Whichever way you choose to wear it, you can\'t go wrong.     28: WAIST:(29") HIP:(35") THIGH:(21") LEG OPENING:(6 1/4")     30:WAIST:(31") HIP:(37") THIGH:(22") LEG OPENING:(6 1/2")     32:WAIST:(33") HIP:(39") THIGH:(23") LEG OPENING:(6 3/4")     34:WAIST:(35") HIP:(41") THIGH:(24") LEG OPENING:(7")     36:WAIST:(37") HIP:(43") THIGH:(25") LEG OPENING:(7 1/4")     38:WAIST:(39") HIP:(45") THIGH:(26") LEG OPENING:(7 1/2")     40:WAIST:(41") HIP:(47") THIGH:(27") LEG OPENING:(7 3/4")     42:WAIST:(43") HIP:(49") THIGH:(28") LEG OPENING:(8")    ',
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Victorious-Men-s-Skinny-Fit-Unwashed-Raw-Denim-Jeans-DL938-Indigo-32-30_e5a876b3-fc35-4f23-a87d-f8fd5266f0a1.35641238d6b80ddbf3d96be00b3c8366.jpeg",
    contact: "+92-272-5969138",
    color: [
      "Black",
      "Black/Timber",
      "Charcoal",
      "Gray",
      "Indigo",
      "Indigo/Timber",
      "Khaki",
      "Wheat",
    ],
    categories: [
      "Clothing",
      "Mens Clothing",
      "Mens Jeans",
      "Mens Slim Fit Jeans",
    ],
    size: [
      "28/30",
      "30/30",
      "30/32",
      "32/30",
      "32/32",
      "34/30",
      "34/32",
      "36/30",
      "36/32",
      "38/30",
      "38/32",
      "40/30",
      "40/32",
      "42/30",
      "42/32",
      "44/30",
      "44/32",
    ],
  },
  {
    id: 24,
    stock: 5,
    name: '16" Handwoven Cotton Throw Pillow Cover with Tufted designs and Side Tassels',
    ratting: 4.4,
    reviews: 8,
    description:
      '16" Handwoven Cotton Throw Pillow Cover with Tufted designs and Side Tassels     Size:&nbsp;16" x 16" square throw pillow   COMPOSITION:&nbsp;Handwoven from 100% cotton by skilled artisans for a designer look and feel   DESIGN:&nbsp;Textured front and solid backside for displaying on your sofa, couch, or bed   IDEAL:&nbsp;Ideal accent for boho, vintage, Moroccan and rustic home decor styles   FEATURES:&nbsp;Invisible back zipper is easy to open and close&nbsp;    Embrace home decor style with the Deerlux Tufted Cotton Pillow Cover. Handmade by skilled artisans&nbsp;in India, size may slightly vary. Its 100% cotton material provides a natural rustic touch and authentic Bohemian flavor. Wash on gentle cycle, cold water and hang to dry. It features tufted pattern and side tassels, making it a perfect home decor accessory for living room sofas, accent chairs, or for dressing up a bed.',
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/16-Handwoven-Cotton-Throw-Pillow-Cover-with-Tufted-designs-and-Side-Tassels_da1a87ba-4fe9-4ca4-a63d-a73690b8ca75.d65a3194f2f276f640145b1e65eeac28.jpeg",
    contact: "+92-128-6857195",
    color: [
      "Border",
      "Border With Cushion",
      "Circle",
      "Circle With Cushion",
      "Dots",
      "Dots With Cushion",
      "Geometric",
      "Geometric With Cushion",
      "Line",
      "Line With Cushion",
      "Star",
      "Star With Cushion",
    ],
    categories: ["Home", "Decor", "Decorative Pillows", "Throw Pillow Covers"],
    size: [
      "Border",
      "Border with Cushion",
      "Circle",
      "Circle with Cushion",
      "Dots",
      "Dots with Cushion",
      "Geometric",
      "Geometric with Cushion",
      "Line",
      "Line with Cushion",
      "Star",
      "Star with Cushion",
    ],
  },
  {
    id: 25,
    stock: 95,
    name: "X RAY JEANS Mens Five Pocket Commuter Pants, Fig, 34X32",
    ratting: 5.0,
    reviews: 1,
    description:
      "These colored mens jeans from XRAY are the perfect addition to any wardrobe. Their versatile design and style fused with dynamic comfort make them great to wear casually or dressed. Their stretch material gives you comfortable flex movement in complete comfort without compromising the look and style. Xray jeans for men have a variety of colors such as black jeans for men, white jeans men, blue jeans men, grey jeans men and much more to give your wardrobe a level up for style. Constructed of 99% cotton and 2% Spandex. This product features high durability cotton fibers and will not lose color over time, even after many washes. A great pair of pants to feel really relaxed in while keeping your fashion look.",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/X-RAY-Jeans-Men-s-Slim-Fit-Skinny-Stretch-Comfy-Denim-Colored-Jeans-Comfortable-Commuter-Pants-Commuter-12038-Fig-34W-X-32L_afc5094d-e9f8-4594-a583-a438ef32618f.bb60805676ab1d923fab886f85b371c7.jpeg",
    contact: "+92-738-9188883",
    color: [
      "Black",
      "FIG",
      "Gray",
      "KHAKI",
      "MIDNIGHT BLUE",
      "NAVY",
      "OLIVE",
      "STONE",
      "White",
    ],
    categories: ["Clothing", "Mens Clothing", "Mens Jeans", "Mens Jeans"],
    size: [
      "28x30",
      "30X30",
      "30X32",
      "32X30",
      "32X32",
      "33X32",
      "34X30",
      "34X32",
      "36X30",
      "36X32",
      "36x34",
      "38X32",
      "38x34",
      "40X32",
      "40x34",
      "42x32",
      "42x34",
      "44x34",
      "46x34",
      "48x34",
    ],
  },
  {
    id: 26,
    stock: 57,
    name: "Exclusivo Mezcla Waffle Textured Soft Fleece Blanket, King Size Bed Blanket, Cozy Warm and Lightweight (Dark Grey, 90x104 inches)",
    ratting: 4.5,
    reviews: 64,
    description:
      "   Soft flannel fleece:This Blankets is made from 100% premium microfiber polyester. The elegantly designed jacquard pattern on the one side, the other side is super smooth flannel.Tightly stitching edges and strong seams make our blanket durable enough to provide you with long term use.   Versatile Usages: This premium bed blanket can be a very useful item to have on hand. Enough weight to keep you comfortable, yet light enough to keep you from breaking out in sweat, suitable for all seasons.   Durable: With the microfiber fabric and strong stitches, this plush blanket is much more durable than most other blankets,it would last a long service life at a good condition.   Decorative: Bed Blanket features a velvet touch softness with rich and inviting designs,featuring a double-faced plush with graceful luster. Easily coordinates or enhances existing bedding or home décor.   Easy Care: No need to spend special effort, this bed blanket is machine washable and dry-able and would hold up well after washing. No shrinkage, No colour fading, and No unravelling.If you have any problems, please feel free to contact us, we will try our best to satisfy you.  ",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Exclusivo-Mezcla-Waffle-Textured-Soft-Fleece-Blanket-King-Size-Bed-Blanket-Cozy-Warm-and-Lightweight-Dark-Grey-90x104-inches_e8bcabf6-6aec-4327-ad71-bbf3cca3991c.13532dd32b058b47be77d559c694302b.jpeg",
    contact: "+92-319-1634592",
    color: [
      "Black",
      "Celadon",
      "Coffee",
      "Dark Grey",
      "Deep Red",
      "Forest Green",
      "Hot Pink",
      "Navy Blue",
      "Slate Blue",
    ],
    categories: ["Home", "Bedding", "Blankets", "Bed Blankets"],
    size: ['90" x 104"', '90" x 66"', '90" x 90"'],
  },
  {
    id: 27,
    stock: 28,
    name: "Anastasia Beverly Hills Norvina PRO Pigment Eyeshadow Palette Vol 3",
    ratting: 4.8,
    reviews: 575,
    description:
      "Anastasia Beverly Hills ABH Norvina Pro Pigment Palette Vol. 3 is a professional-grade artistry palette featuring 25 deluxe-sized, all are high-performance shades. Oversized shadows offer limitless possibilities for your favorite makeup looks. This is the perfect palette for those who like to get truly creative with their eye makeup. This product comes in powders form, 15.75 oz. Will not clog pores, easy to wash off. This is a unisex product. To use apply colors onto eyes, face, and body using a makeup sponge, makeup brush, or fingers. Colors included range from a-1 to e-5 from the Anastasia Beverly Hills collection. This is a dermatologist tested product, cruelty free, vegan. Made without the use of gluten, parabens or phthalates.",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Anastasia-Beverly-Hills-Norvina-PRO-Pigment-Eyeshadow-Palette-Vol-3_68c164ad-4f08-4ebd-ada2-80c7c8b41f72.6ec6e2ed419b92253025416438782964.jpeg",
    contact: "+92-467-2661730",
    color: [],
    categories: ["Beauty", "Makeup", "All Makeup"],
    size: [],
  },
  {
    id: 28,
    stock: 44,
    name: "Amay 800TC Organic Cotton Twin XL Size Fitted Sheet ( 39X80 ) Fits Mattress Upto 21 inches Deep Pocket, Ivory Solid",
    ratting: 5.0,
    reviews: 4,
    description:
      '   100% ORGANIC COTTON - Certified with GOTS (Global Organic Textile Standard), fine yarn (made with long staple cotton fibers) in a single ply is used to make this amazingly soft 800 thread count fabric. Switch to non-toxic &amp; chemical free bedding that is luxurious &amp; durable.   TWIN XL SIZE: 1Pc Fitted Sheet (39" x 80") Fits Mattresses Upto 21 inches Deep Pocket With Elastic All Around the Fitted Sheet !!   MATERIAL &amp; WEAVE: 100% Organic Cotton procured directly from farmers to make this beautiful sheet set in-house. This sheet set is made using PERCALE WEAVE, which gives the sheet crisp and cool attributes. Rest assured, a boon for folks who hate hot sleep!   CERTIFIED STANDARD 100 by OEKO-TEX - All our sheets are MADE IN GREEN and STANDARD 100 by OEKO?TEX. According to the guidelines, these products are tested for harmful substances and produced in an environmentally friendly and socially responsible manner. Each fabric batch is also tested for various durability features such as no-pilling, low shrinkage, color fastness etc., then stitched, individually inspected to be defect free and finally packed for sales   PEACE OF MIND: Our team’s first priority is keeping you happy with your purchase! We are passionate about what we do and proud of the products we offer. If you have any questions or concerns, please don’t hesitate to contact us. We will be quick to respond!   EASY HOME LAUNDRY :- Fitted sheet are machine washable in cold water.These Cotton sheet is quickly dry with fade resistance properties.Do not bleach Organic cotton sheet simple low iron required to make it perfect. Our elastic fitted sheet is easy to care and handle and feel like luxury hotel bedsheets.  ',
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/Amay-800TC-Organic-Cotton-Twin-XL-Size-Fitted-Sheet-39X80-Fits-Mattress-Upto-21-inches-Deep-Pocket-Ivory-Solid_ce4a1f51-cf7c-4f11-be3c-3230c4bd3680.44e2b50485a6acff3aef5f2cd32a5323.jpeg",
    contact: "+92-517-8995611",
    color: [
      "Aqua Blue",
      "Beige",
      "Black",
      "Burgundy",
      "Chocolate",
      "Dark Grey",
      "Gold",
      "Hot Pink",
      "Ivory",
      "Lavender",
      "Light Blue",
      "Navy Blue",
      "Orange",
      "Parrot Green",
      "Peach",
      "Pink",
      "Purple",
      "Red",
      "Royal Blue",
      "Sage",
      "Silver Gray",
      "Silver Grey",
      "Taupe",
      "Teal",
      "Turquoise",
      "White",
      "Wine",
      "Yellow",
    ],
    categories: [
      "Home",
      "Bedding",
      "Bed Sheets & Pillowcases",
      "Cooling Sheets",
    ],
    size: [
      "King Pillowcases(20x40)",
      "Split King (39x80)",
      "Twin (39x75)",
      "Twin XL (39x80)",
      "Full (54x75)",
      "Queen ( 60x80)",
      "RV Short Queen ( 60x75)",
      "Olympic Queen ( 66x80)",
      "California king (72x84)",
      "RV King (72x75)",
      "King (76x80)",
      "Grand King (80x98)",
      "Emperor (84x84)",
      "Alaska King (108x108)",
    ],
  },
  {
    id: 29,
    stock: 126,
    name: "LARACE Women's Plus Size Tops 3/4 Sleeve Tunic Shirts Casual Button V-neck Blouse Black 4X",
    ratting: 4.8,
    reviews: 31,
    description:
      "LARACE, the brand built in 2015. From style design, material choice to workmanship, we pay high attention on every detail, devote ourselves to provide comfortable casual clothes for women, especially for plus size women.  The strong&nbsp;design team&nbsp;always strives the unique charm on clothing and reflect ladies' individual taste in details.  The serious&nbsp;production team&nbsp;keep improving every detail, such as the fabric content, fabric thickness, stitch density, stitching way etc,.  The&nbsp;fabric sourcing team&nbsp;keep researching different fabric's features, such as weight, touching feel, shrinkage rate and durability.     90% Polyester, 10% Spandex. NOTE: size 1X is the same as size XL.   Imported   Button closure   Machine Wash   High Quality Womens Tunic Tops - 90% Polyester, 10% Spandex. LARACE plus size tops for women dressy tees are super soft, light and breathable plaid shirts for women, stretchy womens swing tops for easy wearing. LARACE plus size tunic tops for women are not easy to wrinkle and not clingy.   V Neck Womens Plus Tunic Tops - 3 buttons decorating on the neck of women tops, make the womens plaid shirt out of monotony. Classic V neck LARACE 3/4 sleeve tunics tops, tees &amp; blouses, buffalo plaid tunic with small pleats on the back, make the plus size womens tops simple but fashion.   Plus Size 3/4 Sleeve Tops For Women - The three quarter sleeves tops and blouses, loose waist women plus size clothing, long flowy hem hides belly and hips perfectly, creating particular slimming effect. Nice big womens clothes plus size women's tunics in cool season or as maternity tops.       Easy-matching Plus Size Womens Shirts - LARACE plus size shirts for women are the easy paired t shirts for women in wardrobe. Plus swing tunic tops to wear with leggings, jeans, pants, jacket, cardigan or coat. Plus size long tunics can as basic tees for a chic look in Spring/Fall/Winter.   Casual Tops For Women - Buffalo plaid shirt womens blouses style for daily wear, such as working, dating, parties, travel, family gathering. These womens plus size tops are great plaid tops autumn blouses for women, maternity work tops, or layering womens tunic tops for leggings in winter.  ",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/LARACE-Women-s-Plus-Size-Tops-3-4-Sleeve-Tunic-Shirts-Casual-Button-V-neck-Blouse-Black-4X_c055384d-49e4-4530-9e88-22e6ec93bbc9.bab72ea9604d6e9383461d99ad694003.jpeg",
    contact: "+92-395-5854981",
    color: [
      "2-Black",
      "5-WineRed",
      "A-Navy12",
      "A-WineRed18",
      "Black",
      "Flower42",
      "Flower46",
    ],
    categories: ["Clothing", "Womens Plus", "Plus Size Tops", "Plus Size Tops"],
    size: ["1X", "2X", "3X", "4X"],
  },
  {
    id: 30,
    stock: 49,
    name: "FY24 Valentine's Day Holiday Deals! itsun Lingerie Sets for Women Sexy Plus Size, Women Sexy Lace Lingerie Set Strappy Bra and Panty Set Two Piece Crotchless Lingerie White",
    ratting: 1.3,
    reviews: 3,
    description:
      "Women Sexy Lace Lingerie Set Strappy Bra and Panty Set Two Piece Crotchless Lingerie  Features:   Lightweight,ultra soft could keep you warm all day but stay cool.   Occasion: Daily wear, vocation, Christmas, dates, sports, school, working, street wear,etc. Easy to pair with,, skinny leggings for a trendy look in spring, and winter.   Features: Casual style showing your unique and vitality, add a sense of elegance and style. The casual long-sleeved pullover feels soft and comfortable, and You will it when you receive it.   Kindly note size details vary among different colors. Please check product description for more size information.  Product Description:  Season:All Season  Gender:Women  Occasion:Casual  Material:Lace  Style:Fashion,Home  Length:Regular  Fits:Fits ture to size  How to wash:Hand wash Cold,Hang or Line Dry  What you get:1PC Women Bra+1PC Women Panties  NOTE: Please compare the detail sizes with yours before you buy!!! Use similar clothing to compare with the size  Size: S Size.: Small US: 4 UK: 8 EU: 34 Bust: 68-78cm/26.77-30.71'' Waist: 64-76cm/25.20-29.92''   Size: M Size.: Medium US: 6 UK: 10 EU: 36 Bust: 70-80cm/27.56-31.50'' Waist: 66-78cm/25.98-30.71''   Size: L Size.: Large US: 8 UK: 12 EU: 38 Bust: 72-82cm/28.35-32.28'' Waist: 68-80cm/26.77-31.50''   Size: XL Size.: X-Large US: 10 UK: 14 EU: 40 Bust: 74-84cm/29.13-33.07'' Waist: 70-82cm/27.56-32.28''   Size: XXL Size.: 2X-Large US: 12 UK: 16 EU: 42 Bust: 76-86cm/29.92-33.86'' Waist: 72-84cm/28.35-33.07''   Size: XXXL Size.: 3X-Large US: 14 UK: 18 EU: 44 Bust: 78-88cm/30.71-34.65'' Waist: 74-86cm/29.13-33.86'' ",
    prices: {
      price: 15.99,
      originalPrice: 22.99,
    },
    picture:
      "https://i5.walmartimages.com/seo/FY24-Valentine-s-Day-Holiday-Deals-itsun-Lingerie-Sets-Women-Sexy-Plus-Size-Lace-Set-Strappy-Bra-Panty-Two-Piece-Crotchless-White_5fbb6e98-918d-4b21-92a3-3e90f809d0cb.eba3393f28c4e10df7155d53366070ef.jpeg",
    contact: "+92-243-5363878",
    color: ["Black", "Blue", "Red", "White"],
    categories: [
      "Clothing",
      "Womens Clothing",
      "Womens Bras, Panties & Lingerie",
      "Womens Lingerie",
      "Lingerie Sets",
    ],
    size: ["S", "M", "L", "XL", "XXL", "XXXL"],
  },
];
